# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jobsdb
    ports:
      - 5433:5432

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411