receivers:
  otlp: # the OTLP receiver the app is sending traces to
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp/jaeger: # Jaeger supports OTLP directly
    endpoint: http://jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces/dev:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]